import type { KeysOfUnion } from 'type-fest';
import { objectValues } from '../../lib/object';
import type { RuleDefinition } from '../lib/rule-engine';

const SCALE_ROOT = { color: '1-LIGHT' } as const;
const SCALE_TONE = { color: '2-LIGHT' } as const;
const SCALE_TONE_ALT = { color: '2-LIGHTER', opacity: 0.25 } as const;
const CHORD_ROOT = { color: '1-STRONG' } as const;
const CHORD_TONE = { color: '2-STRONG' } as const;
const CHORD_TONE_ALT = { color: '2-STRONG', opacity: 0.25 } as const;

export const DEFINITIONS_GROUPED = {
  Scales: {
    'Major scale': [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', '3', '4', '5', '6', '7'] },
        ...SCALE_TONE,
      },
    ],
    'Minor scale': [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', 'b3', '4', '5', 'b6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
  },
  'Scales - Modes': {
    Lydian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', '3', '#4', '5', '6', '7'] },
        ...SCALE_TONE,
      },
    ],
    Ionian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', '3', '4', '5', '6', '7'] },
        ...SCALE_TONE,
      },
    ],
    Mixolydian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', '3', '4', '5', '6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
    Dorian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', 'b3', '4', '5', '6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
    Aeolian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['2', 'b3', '4', '5', 'b6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
    Phrygian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['b2', 'b3', '4', '5', 'b6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
    Locrian: [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      {
        condition: { interval: ['b2', 'b3', '4', 'b5', 'b6', 'b7'] },
        ...SCALE_TONE,
      },
    ],
  },
  // @todo Perhaps if we can superimpose conditions, this can be simplified by a lot
  'Arpeggios - Maj7': {
    'Maj7 Arpeggio': [
      { condition: { interval: '1' }, ...SCALE_ROOT },
      { condition: { interval: ['3', '5', '7'] }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (1st position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 5, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st position) + 6-4-3-2 (root position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 5, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...CHORD_ROOT },
    ],
    'Maj7 Arpeggio (1st position) + 4-3-2-1 (3rd inversion)': [
      { condition: { string: 1, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 5, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position) + Left 6-4-3-2 (root position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...CHORD_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position) + Left 4-3-2-1 (3rd inversion)': [
      { condition: { string: 1, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position) + 5-4-3-2 (2nd inversion)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position) + Right 6-4-3-2 (1st inversion)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (1st/2nd position) + Right 4-3-2-1 (root position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
    ],
    'Maj7 Arpeggio (2nd position)': [
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (2nd position) + 6-4-3-2 (1st inversion)': [
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 2, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 5, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...CHORD_TONE },
    ],
    'Maj7 Arpeggio (2nd position) + 5-4-3-2 (3rd inversion)': [
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (2nd position) + 4-3-2-1 (root position)': [
      { condition: { string: 1, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 2, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 5, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (3rd position)': [
      { condition: { string: 1, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (3rd position) + 6-4-3-2 (2nd inversion)': [
      { condition: { string: 1, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (3rd position) + 5-4-3-2 (3rd inversion)': [
      { condition: { string: 1, interval: ['3', '5'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '3' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (3rd position) + 4-3-2-1 (1st inversion)': [
      { condition: { string: 1, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 1, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 2, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 5, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 6, interval: ['3', '5'] }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th position)': [
      { condition: { string: 1, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 3, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: ['5', '7'] }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th position) + 6-4-3-2 (3rd inversion)': [
      { condition: { string: 1, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '5' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th position) + 5-4-3-2 (root position)': [
      { condition: { string: 1, interval: ['5', '7'] }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 3, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 4, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 6, interval: ['5', '7'] }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th position) + 4-3-2-1 (2nd inversion)': [
      { condition: { string: 1, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 1, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 3, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 4, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 6, interval: ['5', '7'] }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position) + Left 6-4-3-2 (3rd inversion)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...CHORD_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position) + Left 4-3-2-1 (2nd inversion)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '3' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position) + 5-4-3-2 (1st inversion)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '3' }, ...CHORD_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position) + Right 6-4-3-2 (root position)': [
      { condition: { string: 1, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
    ],
    'Maj7 Arpeggio (4th/1st position) + Right 4-3-2-1 (3rd inversion)': [
      { condition: { string: 1, interval: '1' }, ...CHORD_ROOT },
      { condition: { string: 1, interval: '7' }, ...SCALE_TONE },
      { condition: { string: 2, interval: '5' }, ...CHORD_TONE },
      { condition: { string: 2, interval: '3' }, ...SCALE_TONE_ALT },
      { condition: { string: 3, interval: '3' }, ...CHORD_TONE_ALT },
      { condition: { string: 3, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 3, interval: '7' }, ...SCALE_TONE_ALT },
      { condition: { string: 4, interval: '7' }, ...CHORD_TONE_ALT },
      { condition: { string: 4, interval: '5' }, ...SCALE_TONE },
      { condition: { string: 5, interval: '3' }, ...SCALE_TONE },
      { condition: { string: 6, interval: '1' }, ...SCALE_ROOT },
      { condition: { string: 6, interval: '7' }, ...SCALE_TONE },
    ],
  },
} as const satisfies Record<string, Record<string, RuleDefinition>>;

export type DefinitionGroupName = keyof typeof DEFINITIONS_GROUPED;

export type DefinitionPresetName = KeysOfUnion<
  (typeof DEFINITIONS_GROUPED)[DefinitionGroupName]
>;

// Flatten for easy lookup
export const DEFINITIONS = objectValues(DEFINITIONS_GROUPED).reduce<
  Record<DefinitionPresetName, RuleDefinition>
>(
  (acc, group) => ({ ...acc, ...group }),
  {} as Record<DefinitionPresetName, RuleDefinition>,
);
